_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: 101
    WITH_IBN: True
    PRETRAIN_PATH: "/home/wuyiming/.cache/torch/checkpoints/resnet101_ibn_a.pth.tar"

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/market1501/bagtricks_R101-ibn"
