_BASE_: "../Base-AGW.yml"

MODEL:
  SAMPLES_PER_BN: 16
  BACKBONE:
    WITH_NL: False

  HEADS:
    POOL_LAYER: "gempoolP"
    NECK_FEAT: "after"
    NUM_CLASSES: 0

  LOSSES:
    NAME: ("ContrastiveLoss", )

    TRI:
      MARGIN: 0.0
      HARD_MINING: False
      SCALE: 1.0

DATALOADER:
  SAMPLER_NAME: "RandomMultipleGallerySampler"

PSEUDO:
  ENABLED: True
  CLUSTER_ITER: 400
  USE_OUTLIERS: True
  WITH_CLASSIFIER: False
  DBSCAN:
    EPS: [0.58, 0.6, 0.62]

SOLVER:
  OPT: "Adam"
  MAX_ITER: 160
  BASE_LR: 0.00035
  IMS_PER_BATCH: 64

  STEPS: [40, 80, 120]
  WARMUP_ITERS: 0

  LOG_PERIOD: 200

  CHECKPOINT_PERIOD: 5

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True
