MODEL:
  META_ARCHITECTURE: Baseline

  BACKBONE:
    NAME: build_resnet_backbone
    DEPTH: 50x
    NORM: FrozenBN
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    PRETRAIN: True

  HEADS:
    NAME: EmbeddingHead
    NORM: syncBN
    NECK_FEAT: after
    EMBEDDING_DIM: 0
    POOL_LAYER: gempool
    CLS_LAYER: linear

  LOSSES:
    NAME: ("CrossEntropyLoss",)

    CE:
      EPSILON: 0.1
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  CROP_SIZE: 224
  SCALE: (0.16, 1.)
  RATIO: (0.75, 1.33333)

  CJ:
    ENABLED: False
    BRIGHTNESS: 0.3
    CONTRAST: 0.3
    SATURATION: 0.1
    HUE: 0.1

DATALOADER:
  PK_SAMPLER: False
  NUM_WORKERS: 8

SOLVER:
  MAX_EPOCH: 100
  FP16_ENABLED: True

  OPT: SGD
  SCHED: CosineAnnealingLR

  BASE_LR: 0.003
  MOMENTUM: 0.99
  NESTEROV: True

  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.
  IMS_PER_BATCH: 128

  ETA_MIN_LR: 0.00003

  WARMUP_FACTOR: 0.1
  WARMUP_EPOCHS: 10

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256
