#!/usr/bin/env bash
echo "Semi-ActiveReID project with DataParallel from begining"
# random
python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/Market1501/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/market1501
python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/DukeMTMC/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/dukemtmc
# python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/MSMT17/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/msmt17 TEST.DO_VAL True
# margin
python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/Market1501/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/market1501  ACTIVE.QUERY_FUNC "MarginSampler"
python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/DukeMTMC/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/dukemtmc  ACTIVE.QUERY_FUNC "MarginSampler"
# python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/MSMT17/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/msmt17 ACTIVE.QUERY_FUNC "MarginSampler" TEST.DO_VAL True
# entropy
python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/Market1501/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/market1501 ACTIVE.QUERY_FUNC "EntropySampler"
python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/DukeMTMC/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/dukemtmc ACTIVE.QUERY_FUNC "EntropySampler"
# python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/MSMT17/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/msmt17 ACTIVE.QUERY_FUNC "EntropySampler" TEST.DO_VAL True
# coreset
python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/Market1501/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/market1501 ACTIVE.QUERY_FUNC "CoresetSampler"
python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/DukeMTMC/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/dukemtmc ACTIVE.QUERY_FUNC "CoresetSampler"
# python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/MSMT17/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/msmt17 ACTIVE.QUERY_FUNC "CoresetSampler" TEST.DO_VAL True
# confidence
python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/Market1501/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/market1501
python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/DukeMTMC/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/dukemtmc
# python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/MSMT17/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/msmt17 TEST.DO_VAL True
# cluster
python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/Market1501/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/market1501 ACTIVE.QUERY_FUNC "ClusterSampler"
python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/DukeMTMC/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/dukemtmc ACTIVE.QUERY_FUNC "ClusterSampler"
# python projects/Semi-ActiveReID/train_net.py --config-file projects/Semi-ActiveReID/configs/MSMT17/BoT_R50.yml ACTIVE.RECTIFY True ACTIVE.BUILD_DATALOADER False ACTIVE.EDGE_PROP True ACTIVE.END_EPOCH 100 OUTPUT_DIR logs/SpCL_SemiActive/BoT_R50_rectify_begin_random/msmt17 ACTIVE.QUERY_FUNC "ClusterSampler" TEST.DO_VAL True