#!/bin/bash
echo "Run SMT ce tri"
python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 1 MODEL.LOSSES.CE.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce1/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 0.5 MODEL.LOSSES.CE.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce1.0_original_setting/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\) MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 1.0 MODEL.LOSSES.CE.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce0.5_original_setting/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\) MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 0.5 MODEL.LOSSES.CE.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_sce/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"SoftEntropyLoss\",\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. MODEL.LOSSES.SCE.TAU 0.5 MODEL.LOSSES.SCE.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce_stri/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"SoftmaxTripletLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 1.0 MODEL.LOSSES.CE.SCALE 1.0 MODEL.LOSSES.STRI.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce_stri/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"SoftmaxTripletLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 1.0 MODEL.LOSSES.CE.SCALE 1.0 MODEL.LOSSES.STRI.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce_stri_3dbscan/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"SoftmaxTripletLoss\"\) PSEUDO.DBSCAN.EPS [0.58,0.6,0.62] SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 0.5 MODEL.LOSSES.CE.SCALE 1.0 MODEL.LOSSES.STRI.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce_stri_3dbscan/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"SoftmaxTripletLoss\"\) PSEUDO.DBSCAN.EPS [0.58,0.6,0.62] MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 0.5 MODEL.LOSSES.CE.SCALE 1.0 MODEL.LOSSES.STRI.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce_hvc_3dbscan/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"HardViewContrastiveLoss\"\) PSEUDO.DBSCAN.EPS [0.58,0.6,0.62] SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 0.5 MODEL.LOSSES.CE.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce0.5_hvc_rho_decay5e-4/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"HardViewContrastiveLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3  MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 0.5 MODEL.LOSSES.CE.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce1.0_hvc_rho_decay5e-4/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"HardViewContrastiveLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3  MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 1.0 MODEL.LOSSES.CE.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce0.5_hvc_rho_decay5e-4/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"HardViewContrastiveLoss\"\) PSEUDO.DBSCAN.EPS [0.7,] MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 0.5 MODEL.LOSSES.CE.SCALE 1.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ice/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CenterContrastiveLoss\",\"HardViewContrastiveLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. PSEUDO.NORM_CENTER False

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce_sce_sstri/market1501 MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"SoftEntropyLoss\",\"SoftSoftmaxTripletLoss\"\) MODEL.LOSSES.SSTRI.SCALE 1.0 MODEL.LOSSES.CE.EPSILON 0.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce-epsilon0.0/market1501 MODEL.LOSSES.CE.EPSILON 0.0

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ice_normfeat/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CenterContrastiveLoss\",\"HardViewContrastiveLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0.

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ice_normfeat_decay5e-4/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CenterContrastiveLoss\",\"HardViewContrastiveLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ice_normfeat_blur/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CenterContrastiveLoss\",\"HardViewContrastiveLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. INPUT.DO_BLUR True

python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce_hvc/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \"(\"CrossEntropyLoss\",\"HardViewContrastiveLoss\")\" PSEUDO.DBSCAN.BASE "rho" PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 0.5 MODEL.LOSSES.CE.SCALE 1.0

# python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_sce_stri/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"SoftEntropyLoss\",\"SoftmaxTripletLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. MODEL.LOSSES.SCE.TAU 0.5 MODEL.LOSSES.SCE.SCALE 1.0 MODEL.LOSSES.CE.SCALE 1.0 MODEL.LOSSES.STRI.SCALE 1.0

# python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce_stri2/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"SoftmaxTripletLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 0.5 MODEL.LOSSES.CE.SCALE 1.0 MODEL.LOSSES.STRI.TAU 0.09 MODEL.LOSSES.STRI.SCALE 1.0

# python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce_sstri/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"SoftSoftmaxTripletLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 0.5 MODEL.LOSSES.CE.SCALE 1.0 MODEL.LOSSES.SSTRI.SCALE 1.0

# python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/Market1501/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce_stri_sstri/market1501 MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"SoftmaxTripletLoss\",\"SoftSoftmaxTripletLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0. MODEL.LOSSES.CE.EPSILON 0.0 MODEL.LOSSES.CE.TAU 0.5 MODEL.LOSSES.CE.SCALE 1.0 MODEL.LOSSES.STRI.SCALE 0.2 MODEL.LOSSES.SSTRI.SCALE 0.8

# python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/DukeMTMC/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce_stri/dukemtmc MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"SoftmaxTripletLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0.
# python projects/SMT/train_net.py --num-gpus 4 --config-file projects/SMT/configs/MSMT17/BoT_R50.yml OUTPUT_DIR logs/SMT/BoT_R50_ce_stri/msmt17 TEST.DO_VAL True MODEL.HEADS.NECK_FEAT "after" MODEL.LOSSES.NAME \(\"CrossEntropyLoss\",\"SoftmaxTripletLoss\"\) PSEUDO.DBSCAN.BASE 'rho' PSEUDO.DBSCAN.RHO 2.2e-3 SOLVER.WARMUP_EPOCHS 10 SOLVER.WEIGHT_DECAY 0. SOLVER.WEIGHT_DECAY_BIAS 0.