_BASE_: "../Base-cap-BoT_R50.yml"

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

PSEUDO:
  WITH_CLASSIFIER: True
  DBSCAN:
    K1: 30
  HG:
    ST_START_EPOCH: 0

TEST:
  EVAL_PERIOD: 10
#   DO_VAL: True

OUTPUT_DIR: "logs/MGH/msmt17/BoT_R50"
