MODEL:
  META_ARCHITECTURE: 'Baseline'

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: 50
    LAST_STRIDE: 1
    WITH_NL: False
    PRETRAIN: True

  HEADS:
    NAME: "BNneckHead"
    POOL_LAYER: "gempool"
    NECK_FEAT: "before"
    CLS_LAYER: "linear"
    NUM_CLASSES: 0

  LOSSES:
    NAME: ("CrossEntropyLoss", "SoftmaxTripletLoss")

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [0.485, 0.456, 0.406]
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 2

PSEUDO:
  ENABLED: True
  CLUSTER_ITER: 2

SOLVER:
  OPT: "Adam"
  MAX_ITER: 100
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [100,]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 0

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 20

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256

CUDNN_BENCHMARK: True


