_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    WITH_NL: False

  HEADS:
    NECK_FEAT: "before"
    NUM_CLASSES: 0

  LOSSES:
    NAME: ("CrossEntropyLoss", "SoftmaxTripletLoss")
    TRI:
      MARGIN: 0.

DATALOADER:
  SAMPLER_NAME: "BalancedIdentitySampler"

PSEUDO:
  ENABLED: True
  CLUSTER_EPOCH: 2
  RESET_OPT: True

SOLVER:
  OPT: "Adam"
  MAX_EPOCH: 100
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.
  IMS_PER_BATCH: 64

  STEPS: [100,]

  WARMUP_ITERS: 0

  CHECKPOINT_PERIOD: 5

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 256

CUDNN_BENCHMARK: True
