_BASE_: "../Base-AGW.yml"

MODEL:
  BACKBONE:
    WITH_NL: False

  HEADS:
    POOL_LAYER: "gempool"
    NECK_FEAT: "before"
    NUM_CLASSES: 0

  LOSSES:
    NAME: ("CrossEntropyLoss", "SoftmaxTripletLoss")
    TRI:
      MARGIN: 0.

DATALOADER:
  SAMPLER_NAME: "BalancedIdentitySampler"

PSEUDO:
  ENABLED: True
  CLUSTER_ITER: 2

SOLVER:
  OPT: "Adam"
  MAX_ITER: 100
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.
  IMS_PER_BATCH: 64

  STEPS: [100,]

  WARMUP_ITERS: 0

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256

CUDNN_BENCHMARK: True


