MODEL:
  META_ARCHITECTURE: 'USL_Baseline'

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: 50
    LAST_STRIDE: 1
    WITH_NL: True
    PRETRAIN: True

  HEADS:
    NAME: "BNneckHead"
    POOL_LAYER: "avgpool"
    NECK_FEAT: "after"
    CLS_LAYER: "linear"
    NUM_CLASSES: 0

  LOSSES:
    NAME: ("ContrastiveLoss",)

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 16

UNSUPERVISED:
  EPS: 0.6
  EPS_GAP: 0.02
  CLUSTER_ITER: 400
  MEMORY_TEMP: 0.05
  MEMORY_MOMENTUM: 0.2

SOLVER:
  OPT: "Adam"
  MAX_ITER: 24000
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [8000, 16000]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 0

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 2000
  IMS_PER_BATCH: 256

CUDNN_BENCHMARK: True


