_BASE_: "../../../configs/Base-bagtricks.yml"

MODEL:
  BACKBONE:
    WITH_NL: False

  HEADS:
    POOL_LAYER: "avgpool"
    NECK_FEAT: "after"
    NUM_CLASSES: 0

  LOSSES:
    NAME: ("CrossEntropyLoss", "HardViewContrastiveLoss")
    CE:
      EPSILON: 0.
      TAU: 0.5

  MEAN_NET: True
  MEAN_NET_ALPHA: 0.999

DATALOADER:
  SAMPLER_NAME: "RandomMultipleGallerySampler"

PSEUDO:
  ENABLED: True
  CLUSTER_EPOCH: 2
  USE_OUTLIERS: False
  WITH_CLASSIFIER: True
  DBSCAN:
    BASE: 'rho'
    RHO: 2.2e-3
    EPS: [ 0.7, ]

INPUT:
  DO_BLUR: True

SOLVER:
  OPT: "Adam"
  MAX_EPOCH: 100
  BASE_LR: 0.00035
  IMS_PER_BATCH: 32
  WEIGHT_DECAY: 0.
  WEIGHT_DECAY_BIAS: 0.

  STEPS: [ 100, ]
  WARMUP_EPOCHS: 10

  LOG_ITERS: 200

  CHECKPOINT_PERIOD: 5
  ITERS_PER_EPOCH: 200

TEST:
  EVAL_PERIOD: 5

CUDNN_BENCHMARK: True
