_BASE_: "../../../configs/Base-bagtricks.yml"

MODEL:
  BACKBONE:
    WITH_NL: False

  HEADS:
    POOL_LAYER: "avgpool"
    NECK_FEAT: "before"
    NUM_CLASSES: 0

  LOSSES:
    NAME: ("CrossEntropyLoss", "SoftEntropyLoss", "SoftmaxTripletLoss", "SoftSoftmaxTripletLoss")
    CE:
      SCALE: 0.5
    SCE:
      SCALE: 0.5
    STRI:
      SCALE: 0.2
    SSTRI:
      SCALE: 0.8
    
  MEAN_NET: True
  MEAN_NET_ALPHA: 0.999

DATALOADER:
  SAMPLER_NAME: "RandomMultipleGallerySampler"

PSEUDO:
  ENABLED: True
  CLUSTER_EPOCH:  2
  USE_OUTLIERS: False
  WITH_CLASSIFIER: True
  DBSCAN:
    EPS: [0.7,]

SOLVER:
  OPT: "Adam"
  MAX_EPOCH: 100
  BASE_LR: 0.00035
  IMS_PER_BATCH: 64

  STEPS: [100,]
  WARMUP_EPOCHS: 0

  LOG_ITERS: 200

  CHECKPOINT_PERIOD: 5
  ITERS_PER_EPOCH: 200

TEST:
  EVAL_PERIOD: 5

CUDNN_BENCHMARK: True
