_BASE_: "../Base-usl.yml"

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

UNSUPERVISED:
  CLUSTER_ITER: 800

SOLVER:
  MAX_ITER: 48000
  STEPS: [16000, 32000]

OUTPUT_DIR: "logs/msmt17/usl_R50"
