_BASE_: "../Base-usl.yml"

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

UNSUPERVISED:
  CLUSTER_ITER: 800

SOLVER:
  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 5

OUTPUT_DIR: "logs/SpCL/msmt17/usl_R50"
