_BASE_: "Base-bagtricks.yml"

MODEL:
  HEADS:
    NAME: "DCTEmbeddingHead"

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")
    CE:
      EPSILON: 0.1
      SCALE: 1.0

    TRI:
      MARGIN: 0.0
      HARD_MINING: False
      SCALE: 1.0
TEST:
  METRIC: "euclidean"
