_BASE_: "Base-Strongerbaseline.yml"

MODEL:
  META_ARCHITECTURE: 'MGN'

  OPEN_LAYERS: ["b1_pool", "b1_head", "b2_pool", "b2_head", "b21_pool", "b21_head", "b22_pool", "b22_head",
                "b3_pool", "b3_head", "b31_pool", "b31_head", "b32_pool", "b32_head", "b33_pool", "b33_head"]

  BACKBONE:
    WITH_NL: False

  HEADS:
    EMBEDDING_DIM: 256

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)
    CE:
      EPSILON: 0.1
      SCALE: 1.0

    TRI:
      MARGIN: 0.0
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.0

