MODEL:
  META_ARCHITECTURE: "Baseline"

  BACKBONE:
    NAME: "build_resnet_backbone"
    NORM: "BN"
    DEPTH: 50
    LAST_STRIDE: 1
    WITH_IBN: False
    PRETRAIN: True

  HEADS:
    NAME: "BNneckHead"
    NORM: "BN"
    POOL_LAYER: "avgpool"
    NECK_FEAT: "before"
    CLS_LAYER: "linear"
    MARGIN: 0.15
    SCALE: 128

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [0.485, 0.456, 0.406]
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 2

SOLVER:
  OPT: "Adam"
  MAX_ITER: 90
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  HEADS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  SCHED: "WarmupMultiStepLR"
  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256

CUDNN_BENCHMARK: True

