_BASE_: "../Base-AGW.yml"

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  LOSSES:
    TRI:
      HARD_MINING: False
      MARGIN: 0.0

DATASETS:
  NAMES: ("VeRiWild",)
  TESTS: ("SmallVeRiWild", "MediumVeRiWild", "LargeVeRiWild",)

SOLVER:
  OPT: "Adam"
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005

  IMS_PER_BATCH: 64
  MAX_ITER: 60
  STEPS: [30, 50]
  WARMUP_ITERS: 0

  CHECKPOINT_PERIOD: 20

TEST:
  EVAL_PERIOD: 20
  IMS_PER_BATCH: 128

OUTPUT_DIR: "logs/veriwild/agw_R50"
