MODEL:
  META_ARCHITECTURE: 'Baseline'

  BACKBONE:
    NAME: "build_resnet_backbone"
    NORM: "BN"
    DEPTH: "50x"
    LAST_STRIDE: 1
    WITH_IBN: False
    PRETRAIN: True

  HEADS:
    NAME: "HCTHead"
    NORM: "BN"
    POOL_LAYER: "avgpool"
    NECK_FEAT: "before"
    CLS_LAYER: "linear"

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  REA:
    ENABLED: FALSE
    PROB: 0.5
    MEAN: [0.485, 0.456, 0.406]
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPT: "SGD"
  MAX_EPOCH: 200
  BASE_LR: 6e-5
  HEADS_LR_FACTOR: 10.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [201]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 0

  LOG_ITERS: 200
  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256
  METRIC: "euclidean"

CUDNN_BENCHMARK: True


