_BASE_: "../Base-MGN.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN_PATH: "/home/wuyiming/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: "logs/msmt17/mgn_R50-ibn"
